language: node_js
node_js: stable
install:
  - npm ci
script:
  - npm run generate
deploy:
  provider: pages
  local_dir: ./dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
